# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GAHack-Team4-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GAHack-Team4-iOS
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
end
